name = "fampam-restaurant"
compatibility_date = "2024-05-26"
main = "src/worker.ts"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "fampam-restaurant-admin-db"
database_id = "4996a0e1-f22e-4be9-a00e-54128c64a646"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "fampam-assets"

[vars]
ADMIN_EMAIL = "admin@fampam.de"
ADMIN_PASSWORD = "Fampam@123"
# JWT_SECRET = "..." # Set this via Cloudflare Dashboard or .dev.vars
RESEND_API_KEY = "re_MPRiKKgz_DUAo9zPXNtWXMW1UTHkuCZA1"
# STRIPE_SECRET_KEY = "sk_test_..." # Set this via Cloudflare Dashboard or .dev.vars
# STRIPE_WEBHOOK_SECRET = "whsec_..." # Set this via Cloudflare Dashboard or .dev.vars
# STRIPE_PUBLIC_KEY = "pk_test_..." # Set this via Cloudflare Dashboard or .dev.vars
DEV_MODE = "true"

[[send_email]]
name = "SEND_EMAIL"
